
AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

  Exclude:
  - "dato.gemspec"

Style/SafeNavigation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/LineLength:
  Exclude:
  - "spec/**/*"
  - "lib/dato/site/repo/*"
  - "lib/dato/account/repo/*"
  - "lib/dato/account/repo/*"
  - "dato.gemspec"

Metrics/ParameterLists:
  Exclude:
  - "lib/dato/local/field_type/*"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/AndOr:
  EnforcedStyle: conditionals

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
