
AllCops:
  TargetRubyVersion: 2.3

  Exclude:
  - "dato.gemspec"

Style/SafeNavigation:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 8

Metrics/LineLength:
  Exclude:
  - "spec/**/*"
  - "lib/dato/site/repo/*"
  - "lib/dato/account/repo/*"
  - "lib/dato/account/repo/*"
  - "dato.gemspec"

Metrics/ParameterLists:
  Exclude:
  - "lib/dato/local/field_type/*"
