language: ruby
rvm:
  - 2.4.0
  - 2.5.0
  - 2.6.0
before_install:
  - gem install bundler -v 1.13.5
  - echo 'puts "ruby \"#{RUBY_VERSION}\""' | ruby >> Gemfile
  - cat Gemfile
script: rubocop && rake